###

POST http://localhost:8080/account/register
content-type: application/json

{
    "email": "contact.ezgroup@gmail.com",
    "password": "123123",
    "password_confirm": "123123",
    "name": "Kuo Nhan Dung",
    "location": "Illinois St",
    "phone": "0767916592",
    "role": "customer"
}

###
 
POST http://localhost:8080/account/login
content-type: application/json 

{
    "email": "nkeyskuo124@gmail.com",
    "password": "123123"
}

###

POST https://sud-delirate.onrender.com/account/confirm_otp
content-type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Imhhc2hlZF9lbWFpbCI6IjRjZGFhMGUwMTExMGUzZDY0OTE2ZGY1ZDJiYzA0NGNjIiwibmFtZSI6Ikt1byBOaGFuIER1bmciLCJsb2NhdGlvbiI6IklsbGlub2lzIFN0IiwicGhvbmUiOiIwNzY3OTE2NTkyIiwicm9sZSI6ImN1c3RvbWVyIn0sImNvZGUiOjY2MTIsImlhdCI6MTY5ODUwMzE4Mn0.3AHXFCRUZeTOzfL-o06mYMVKIGkC-qk3bx-fTjj7o-c

{
    "code": "6612"
}


###

POST https://sud-delirate.onrender.com/account/register
content-type: application/json

{
    "email": "nkeyskuo124@gmail.com",
    "password": "123123",
    "password_confirm": "123123",
    "name": "Kuo Nhan Dung",
    "location": "Illinois St",
    "phone": "0767916592",
    "role": "customer"
}


###
POST https://sud-delirate.onrender.com/account/login
content-type: application/json 

{
    "email": "nkeyskuo124@gmail.com",
    "password": "123123"
}
