###

GET https://sud-delirate.onrender.com/item/get_item_info/I1698001347001479009

###

GET https://sud-delirate.onrender.com/item/get_all_items

###

POST https://sud-delirate.onrender.com/item/create_item