###

POST http://localhost:8080/order/create
content-type: application/json

{
    "store_id": "653d18ac6c4d593e8018e27d",
    "name": "Lê Gia Phú",
    "phone": "0767916592",
    "email": "phule123@gmail.com",
    "address": "Q4 TPHCM",
    "items": [
        {
            "info": "654cd14ee835494aadb67969",
            "qty": 2,
            "price": 120
        }
    ],
    "note": "Buying pokeball",
    "total_cost": 240,
    "payment_type": "Banking"
}

###

PUT http://localhost:8080/order/tracking_delivery/QC5108003
content-type: application/json

{
    "status": "Transiting",
    "note": "Warehouse transit",
    "location": "Warehouse A2 IL 60070",
    "track_signer": "65452dfd16312eb6d2955104"
}

###


GET http://localhost:8080/order/get_order_info/QC5108003


###

GET http://localhost:8080/order/get_orders_by_customer/6547dc1d9cba75cd29986804

###

GET http://localhost:8080/order/get_orders_by_store/6535707330ae787533e5e631
###

GET http://localhost:8080/order/verify_origin/QC5108003